### ISSUE TITLE
Can we relicense to GPL2-or-GPL3 dual-licensing?

### ISSUE THREAD

**Issue by ghost** [mdoucha/docbook-tools#1]
Hi @mdoucha , we are finally at the point where we'd like to ship this script directly as part of DAPS, in the DAPS package. (So far, we only had it as part of our CI process where it's been serving us well, thank you!)

However, the DAPS package is GPL2+3 dual-licensed. Would you agree to allow us to include the script under this dual license?

[ cc @fsundermeyer ]

**Comment by mdoucha** [comment]
Sure, you have my permission.

**Comment by ghost** [comment]
Thank you!

**Comment by ghost** [comment]
Integrated via https://github.com/openSUSE/daps/commit/8f4d286f3c52619ede89a29589019101c4df4811
